apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-counter
  labels:
    project: counter
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      project: counter
      app: counter
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        project: counter
        app: counter
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: counter
          image: ondrejsika/counter
          resources:
            requests:
              cpu: 20m
              memory: 10Mi
          env:
            - name: REDIS
              value: {{ .Release.Name }}-redis
          ports:
            - containerPort: 80
