apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    release: {{ .Release.Name }}
    project: counter
spec:
  serviceName: redis
  {{ if .Values.persistance }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  {{ end }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      project: counter
      app: redis
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        project: counter
        app: redis
    spec:
      {{ if .Values.persistance }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
      {{ end }}
      containers:
        - name: redis
          image: redis:alpine
          {{ if .Values.persistance }}
          args:
            - redis-server
            - --appendonly
            - "yes"
          volumeMounts:
            - name: data
              mountPath: /data
          {{ end }}
          resources:
            requests:
              cpu: 30m
              memory: 50Mi
            limits:
              cpu: 30m
              memory: 50Mi
          ports:
            - containerPort: 6379
